# 1. Input
input {
  file {
    # 도커 컨테이너 안에서 바라보는 우리 로그 파일의 위치
    path => "/logs/*/*.log"
    sincedb_path => "/usr/share/logstash/data/sincedb"
    # 처음 켤 때 파일의 맨 처음부터 끝까지 싹 다 읽어오라는 뜻
    start_position => "beginning"

    # 파일이 끝났는지 확인하는 주기 (기본 1초에 한 번씩 감시)
    stat_interval => 1
  }
}

# 2. Filter
filter {
  if [log][file][path] {
    dissect {
      mapping => {
        "[log][file][path]" => "/logs/%{[service][name]}/%{log_file_name}"
      }
    }
  } else if [path] {
    dissect {
      mapping => {
        "path" => "/logs/%{[service][name]}/%{log_file_name}"
      }
    }
  }

  if ![service][name] {
    mutate {
      add_field => {
        "[service][name]" => "unknown"
      }
    }
  }

  mutate {
    lowercase => ["[service][name]"]
  }
}

# 3. Output
output {
  # 우리의 목적지인 엘라스틱서치로 보냄
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    # 엘라스틱서치에 저장될 인덱스 이름! 날짜별로 분류함
    index => "swtp-logs-%{[service][name]}-%{+YYYY.MM.dd}"
  }

  # 잘 전송되고 있는지 도커 콘솔 화면에서도 확인하기 위해 추가
  stdout { codec => rubydebug }
}
